name: Armstrong - Open Source News Platform
markdown: redcarpet
pygments: true
encoding: utf-8
exclude: [
	"CNAME",
	"Gemfile",
	"Gemfile.lock",
	"bower.json",
	"bower_components",
	"package.json",
	"node_modules",
	"Gruntfile.js",
	"assets_src",
	"README.rst"]
